### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by RuthSalvador** [DianaMS/LIM012-data-lovers#1]
Objetivos de aprendizaje pendientes:

- HTML y CSS [Entender como funciona flexbox en CSS]
- JavaScript [Entender la diferencia entre expression y statements.] [link](https://lms.laboratoria.la/cohorts/lim-2020-01-bc-core-lim012/courses/javascript/03-functions/01-classic)

**Comment by DianaMS** [comment]
![unnamed](https://user-images.githubusercontent.com/60928490/93678062-928ab100-fa72-11ea-81d9-b548131b071e.png)
![figma](https://user-images.githubusercontent.com/60928490/91101815-7fc8bc00-e62d-11ea-9582-a318200c272d.png)
![canva](https://user-images.githubusercontent.com/60928490/91101826-85260680-e62d-11ea-8b68-59a70e18a44c.png)
![photoshop](https://user-images.githubusercontent.com/60928490/91101834-8a835100-e62d-11ea-9642-ee646b8b88b7.png)
![illustrator](https://user-images.githubusercontent.com/60928490/91101843-8d7e4180-e62d-11ea-964a-157fd2fa67f8.png)
![trello](https://user-images.githubusercontent.com/60928490/91101847-90793200-e62d-11ea-866b-c359b7d0086b.png)
![javascript](https://user-images.githubusercontent.com/60928490/91101862-98d16d00-e62d-11ea-8401-7bee0e4148f8.png)
![html](https://user-images.githubusercontent.com/60928490/91101868-9b33c700-e62d-11ea-9083-d45d26bc41cb.png)
![css](https://user-images.githubusercontent.com/60928490/91101878-9d962100-e62d-11ea-9237-dd655209d089.png)
![typescript](https://user-images.githubusercontent.com/60928490/91102255-6ecc7a80-e62e-11ea-8564-6de69450a6fb.png)
![node](https://user-images.githubusercontent.com/60928490/91102261-71c76b00-e62e-11ea-851b-416ec82ec1b8.png)
![express](https://user-images.githubusercontent.com/60928490/91102309-86a3fe80-e62e-11ea-9979-76d09b2cec8c.png)
![sass](https://user-images.githubusercontent.com/60928490/91102314-8a378580-e62e-11ea-85fd-d178fffe8e06.png)
![react](https://user-images.githubusercontent.com/60928490/91102321-8d327600-e62e-11ea-8a20-9305cd0c7116.png)
![angular](https://user-images.githubusercontent.com/60928490/91102331-915e9380-e62e-11ea-9821-b749bd9dcb27.png)
![firebase](https://user-images.githubusercontent.com/60928490/91102342-97ed0b00-e62e-11ea-8ba3-39beb768b28b.png)
![mongo](https://user-images.githubusercontent.com/60928490/91102347-9d4a5580-e62e-11ea-938c-abb5ffcf18b6.png)
![aws](https://user-images.githubusercontent.com/60928490/91102356-a0dddc80-e62e-11ea-98e1-53dbfb39e136.png)
![docker](https://user-images.githubusercontent.com/60928490/91102365-a5a29080-e62e-11ea-8e34-d91f7b7cc17b.png)
![webpack](https://user-images.githubusercontent.com/60928490/91102375-a9ceae00-e62e-11ea-8985-136d868b7467.png)
![eslint](https://user-images.githubusercontent.com/60928490/91102383-ac310800-e62e-11ea-9fb3-2727326e355a.png)
![git](https://user-images.githubusercontent.com/60928490/91102392-b0f5bc00-e62e-11ea-9676-f990132f138e.png)
![github](https://user-images.githubusercontent.com/60928490/91102398-b3581600-e62e-11ea-9cb2-e08ca858e4f1.png)
![postman](https://user-images.githubusercontent.com/60928490/91102401-b521d980-e62e-11ea-8839-61041920bff1.png)

**Comment by DianaMS** [comment]
![DEU](https://user-images.githubusercontent.com/60928490/103485398-f5a31800-4dc3-11eb-8be4-951c30a23471.png)
![DZA](https://user-images.githubusercontent.com/60928490/103485399-f63bae80-4dc3-11eb-86ee-f5a3099f037a.png)
![ESP](https://user-images.githubusercontent.com/60928490/103485400-f63bae80-4dc3-11eb-8e44-6f1361eb73e6.png)
![FRA](https://user-images.githubusercontent.com/60928490/103485401-f6d44500-4dc3-11eb-918b-adb68b96e518.png)
![USA](https://user-images.githubusercontent.com/60928490/103485402-f6d44500-4dc3-11eb-920b-1f4b122e62b0.png)

**Comment by DianaMS** [comment]
![S_SDG_inverted_WEB-02](https://user-images.githubusercontent.com/60928490/103490415-a53eb100-4de9-11eb-9589-e511fa3674df.png)
![S_SDG_inverted_WEB-03](https://user-images.githubusercontent.com/60928490/103490416-a66fde00-4de9-11eb-9a9a-6804dd0857de.png)
![S_SDG_inverted_WEB-04](https://user-images.githubusercontent.com/60928490/103490417-a7087480-4de9-11eb-8699-5217ca16c6e3.png)
![S_SDG_inverted_WEB-05](https://user-images.githubusercontent.com/60928490/103490418-a7087480-4de9-11eb-9752-6db52c69f33a.png)
![S_SDG_inverted_WEB-06](https://user-images.githubusercontent.com/60928490/103490420-a7a10b00-4de9-11eb-81ff-3273259e5431.png)
![S_SDG_inverted_WEB-07](https://user-images.githubusercontent.com/60928490/103490421-a839a180-4de9-11eb-8f73-3c45e5c001ed.png)
![S_SDG_inverted_WEB-08](https://user-images.githubusercontent.com/60928490/103490422-a8d23800-4de9-11eb-9e5c-49fc9aebdff8.png)
![S_SDG_inverted_WEB-09](https://user-images.githubusercontent.com/60928490/103490423-a96ace80-4de9-11eb-971c-76672f9e7421.png)
![S_SDG_inverted_WEB-10](https://user-images.githubusercontent.com/60928490/103490424-aa036500-4de9-11eb-9b65-c320de17f6f2.png)
![S_SDG_inverted_WEB-11](https://user-images.githubusercontent.com/60928490/103490426-aa9bfb80-4de9-11eb-82bc-07799109e1ef.png)
![S_SDG_inverted_WEB-12](https://user-images.githubusercontent.com/60928490/103490427-ab349200-4de9-11eb-9547-fb6a98326a5a.png)
![S_SDG_inverted_WEB-13](https://user-images.githubusercontent.com/60928490/103490428-abcd2880-4de9-11eb-835d-b8581fd7ac83.png)
![S_SDG_inverted_WEB-14](https://user-images.githubusercontent.com/60928490/103490430-ac65bf00-4de9-11eb-8d14-6a110bcc53c7.png)
![S_SDG_inverted_WEB-15](https://user-images.githubusercontent.com/60928490/103490431-acfe5580-4de9-11eb-9dd8-a202ca0477eb.png)
![S_SDG_inverted_WEB-16](https://user-images.githubusercontent.com/60928490/103490432-ad96ec00-4de9-11eb-8a4c-5e69595b8230.png)
![S_SDG_inverted_WEB-17](https://user-images.githubusercontent.com/60928490/103490433-ae2f8280-4de9-11eb-9277-23e07c65cc9a.png)
![S_SDG_inverted_WEB-01](https://user-images.githubusercontent.com/60928490/103490434-aec81900-4de9-11eb-8f9d-cafa4e7b4cb2.png)

**Comment by DianaMS** [comment]
![Bitbucket](https://user-images.githubusercontent.com/60928490/116787352-21c86000-aa69-11eb-9016-90ad87c1845c.png)

![NetCore](https://user-images.githubusercontent.com/60928490/116787086-bc27a400-aa67-11eb-9a68-a15dea01eb43.png)
![SQLServer](https://user-images.githubusercontent.com/60928490/116787087-bcc03a80-aa67-11eb-8da7-907a3da99ec1.png)
![C#](https://user-images.githubusercontent.com/60928490/116787088-bcc03a80-aa67-11eb-8ab1-bf138c1e2270.png)

![PowerBI](https://user-images.githubusercontent.com/60928490/116787356-24c35080-aa69-11eb-8ea9-83ff89ace141.png)
